---
title: "Filtering_Oberauer2019"
author: "Chenyu"
date: "20/05/2024"
output:
  html_document:
  toc: yes
editor_options: 
  chunk_output_type: console
---

## 1.1 Clear workspace and set default colors

```{r reset, include=FALSE}
# Clear all plots and variables from workspace
graphics.off()
rm(list=ls(all.names=TRUE))

# Set numerical precision and color schemes
options(digits = 3)
options(ggplot2.discrete.colour= c("#615F63","#FF7F6F","#2F7FC1","#FFBE7A","#8FC0A9","#8A1C56"))
options(ggplot2.discrete.fill= c("#615F63","#FF7F6F","#2F7FC1","#FFBE7A","#8FC0A9","#8A1C56"))
```

## 1.2 Import functions and packages

```{r}
# Install and load required packages
packages = c(
  # CRAN packages for data analysis and visualization
  "tidyverse", "brms", "ggpubr", "tidybayes", "bayestestR",
  # Github packages for specialized functions
  "chenyu-psy/smartr@v0.2.2", 
  "venpopov/bmm"
)
process_packages(packages, quietly = TRUE)

# Source all local R functions from the functions directory
load_functions("./functions")


# task name
task = "OL2019"
model_path <- str_glue("./models/models_{task}/")
sample_path <- str_glue("./models/sample_{task}/")
figure_path <- str_glue("./figures/figures_{task}/")
# 
# # check whether the folders are existent or not. If not, create a new one
dir.create(file.path(model_path), showWarnings = FALSE)
dir.create(file.path(sample_path), showWarnings = FALSE)
dir.create(file.path(figure_path), showWarnings = FALSE)

```

# 2 Import data
```{r}

Data_Exp3 <- read_csv("./data/OberauerLewandowsky_2019/Data_Exp3.csv")
Data_Exp4 <- read_csv("./data/OberauerLewandowsky_2019/Data_Exp4.csv")

```

# 3 M3 (parameters ra, rc)

## 3.1 Data preprocessing

```{r}

mData_Exp3 <- Data_Exp3 %>% 
  mutate(
    participant = factor(participant),
    cue = factor(cue),
    freetime = factor(freetime)
  )

contrasts(mData_Exp3$cue) <- bayestestR::contr.equalprior(2)
contrasts(mData_Exp3$freetime) <- bayestestR::contr.equalprior(2)

mData_Exp4 <- Data_Exp4 %>% 
  mutate(
    participant = factor(participant),
    cue = factor(cue),
    freetime = factor(freetime)
  )

contrasts(mData_Exp4$cue) <- bayestestR::contr.equalprior(2)
contrasts(mData_Exp4$freetime) <- bayestestR::contr.equalprior(2)

```

## 3.2 Formula function

```{r}

Formula_M3 <- bmf(
  Correct ~ a + c + b,
  Other ~ a + b,
  Dist ~ ra*a + rc*c + b,
  OtherDist ~ ra*a + b,
  NPL ~ b,
  a ~ 0 + cue:freetime + (0 + cue:freetime || participant),
  c ~ 0 + cue:freetime + (0 + cue:freetime || participant),
  ra ~ 0 + cue:freetime + (0 + cue:freetime || participant),
  rc ~ 0 + cue:freetime + (0 + cue:freetime || participant)
)


```

## 3.3 Model function

```{r}

Par_M3 <- m3(
  resp_cats = c("Correct","Other","Dist","OtherDist","NPL"),
  num_options = c("nCorrect","nOther","nDist","nOtherDist","nNPL"),
  choice_rule = "softmax",
  links = list(
    a = "identity",
    c = "identity",
    ra = "logit",
    rc = "logit"),
  default_priors = list(
    a = list(main = "normal(3,1)", effect = "normal(3,1)"),
    c = list(main = "normal(3,1)", effect = "normal(3,1)"),
    ra = list(main = "logistic(0,1)", effect = "logistic(0,1)"),
    rc = list(main = "logistic(0,1)", effect = "logistic(0,1)"))
  )


```


## 3.4 Model Fit

### 3.4.1 Experiment 3

```{r}

smart_runFun(
  fun = bmm,
  args = list(
    formula = Formula_M3,
    data = mData_Exp3,
    model = Par_M3,
    chains = 8,
    iter = 10000,
    warmup = 2500,
    cores = 8,
    control = list(adapt_delta = 0.95, max_treedepth = 15),
    save_pars = save_pars(all = TRUE),
    sample_prior = "yes",
    backend = "cmdstanr",
    file = paste0(model_path, "Model_M3_OL2019_Exp3.rds")
  ),
  name = "Model_M3_OL2019_Exp3"
)


```


### 3.4.2 Experiment 4
```{r}

smart_runFun(
  fun = bmm,
  args = list(
    formula = Formula_M3,
    data = mData_Exp4,
    model = Par_M3,
    chains = 8,
    iter = 10000,
    warmup = 2500,
    cores = 8,
    control = list(adapt_delta = 0.95, max_treedepth = 15),
    save_pars = save_pars(all = TRUE),
    sample_prior = "yes",
    backend = "cmdstanr",
    file = paste0(model_path, "Model_M3_OL2019_Exp4.rds")
  ),
  name = "Model_M3_OL2019_Exp4"
)


```


## 3.5 Bayes Factor

```{r}

Model_OL2019_Exp3 <- str_glue("{model_path}Model_M3_OL2019_Exp3.rds") %>% readRDS()

Hyp_Model_OL2019_Exp3 <- Model_OL2019_Exp3 %>% 
  hypothesis(c(
    a_cue_short = "a_cuepostcue:freetimeshort = a_cueprecue:freetimeshort",
    a_cue_long = "a_cuepostcue:freetimelong = a_cueprecue:freetimelong",
    c_cue_short = "c_cuepostcue:freetimeshort = c_cueprecue:freetimeshort",
    c_cue_long = "c_cuepostcue:freetimelong = c_cueprecue:freetimelong",
    ra_cue_short = "inv_logit(ra_cuepostcue:freetimeshort) = inv_logit(ra_cueprecue:freetimeshort)",
    ra_cue_long = "inv_logit(ra_cuepostcue:freetimelong) = inv_logit(ra_cueprecue:freetimelong)",
    rc_cue_short = "inv_logit(rc_cuepostcue:freetimeshort) = inv_logit(rc_cueprecue:freetimeshort)",
    rc_cue_long = "inv_logit(rc_cuepostcue:freetimelong) = inv_logit(rc_cueprecue:freetimelong)",
    
    a_short_pre = "a_cueprecue:freetimeshort = a_cueprecue:freetimelong",
    a_short_post = "a_cuepostcue:freetimeshort = a_cuepostcue:freetimelong",
    c_short_pre = "c_cueprecue:freetimeshort = c_cueprecue:freetimelong",
    c_short_post = "c_cuepostcue:freetimeshort = c_cuepostcue:freetimelong",
    ra_short_pre = "inv_logit(ra_cueprecue:freetimeshort) = inv_logit(ra_cueprecue:freetimelong)",
    ra_short_post = "inv_logit(ra_cuepostcue:freetimeshort) = inv_logit(ra_cuepostcue:freetimelong)",
    rc_short_pre = "inv_logit(rc_cueprecue:freetimeshort) = inv_logit(rc_cueprecue:freetimelong)",
    rc_short_post = "inv_logit(rc_cuepostcue:freetimeshort) = inv_logit(rc_cuepostcue:freetimelong)"
  ))

Hyp_Model_OL2019_Exp3$hypothesis %>% mutate(Evid.Ratio = 1/Evid.Ratio)

#       Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio Post.Prob Star
# 1    a_cue_short  -1.0057     0.507   -2.037  -0.0377      2.627     0.276    *
# 2     a_cue_long  -0.3389     0.588   -1.506   0.8152      0.483     0.674     
# 3    c_cue_short  -0.0134     0.345   -0.694   0.6598      0.242     0.805     
# 4     c_cue_long   0.1508     0.320   -0.480   0.7856      0.256     0.796     
# 5   ra_cue_short   0.1123     0.110   -0.112   0.3209      0.472     0.679     
# 6    ra_cue_long   0.3007     0.144    0.033   0.6026      3.919     0.203    *
# 7   rc_cue_short  -0.0403     0.118   -0.263   0.1952      0.309     0.764     
# 8    rc_cue_long   0.0309     0.109   -0.191   0.2304      0.284     0.779     
# 9    a_short_pre  -0.1512     0.620   -1.378   1.0563      0.435     0.697     
# 10  a_short_post  -0.8180     0.466   -1.778   0.0631      1.674     0.374     
# 11   c_short_pre  -0.0944     0.312   -0.706   0.5231      0.228     0.815     
# 12  c_short_post  -0.2585     0.352   -0.951   0.4397      0.326     0.754     
# 13  ra_short_pre   0.1238     0.140   -0.133   0.4218      0.457     0.686     
# 14 ra_short_post  -0.0646     0.115   -0.295   0.1577      0.312     0.762     
# 15  rc_short_pre   0.0441     0.119   -0.195   0.2667      0.315     0.760     
# 16 rc_short_post  -0.0271     0.109   -0.226   0.1971      0.290     0.775  

Model_OL2019_Exp4 <- str_glue("{model_path}Model_M3_OL2019_Exp4.rds") %>% readRDS()

Hyp_Model_OL2019_Exp4 <- Model_OL2019_Exp4 %>% 
  hypothesis(c(
    a_cue_short = "a_cuepostcue:freetimeshort = a_cueprecue:freetimeshort",
    a_cue_long = "a_cuepostcue:freetimelong = a_cueprecue:freetimelong",
    c_cue_short = "c_cuepostcue:freetimeshort = c_cueprecue:freetimeshort",
    c_cue_long = "c_cuepostcue:freetimelong = c_cueprecue:freetimelong",
    ra_cue_short = "inv_logit(ra_cuepostcue:freetimeshort) = inv_logit(ra_cueprecue:freetimeshort)",
    ra_cue_long = "inv_logit(ra_cuepostcue:freetimelong) = inv_logit(ra_cueprecue:freetimelong)",
    rc_cue_short = "inv_logit(rc_cuepostcue:freetimeshort) = inv_logit(rc_cueprecue:freetimeshort)",
    rc_cue_long = "inv_logit(rc_cuepostcue:freetimelong) = inv_logit(rc_cueprecue:freetimelong)",
    
    a_short_pre = "a_cueprecue:freetimeshort = a_cueprecue:freetimelong",
    a_short_post = "a_cuepostcue:freetimeshort = a_cuepostcue:freetimelong",
    c_short_pre = "c_cueprecue:freetimeshort = c_cueprecue:freetimelong",
    c_short_post = "c_cuepostcue:freetimeshort = c_cuepostcue:freetimelong",
    ra_short_pre = "inv_logit(ra_cueprecue:freetimeshort) = inv_logit(ra_cueprecue:freetimelong)",
    ra_short_post = "inv_logit(ra_cuepostcue:freetimeshort) = inv_logit(ra_cuepostcue:freetimelong)",
    rc_short_pre = "inv_logit(rc_cueprecue:freetimeshort) = inv_logit(rc_cueprecue:freetimelong)",
    rc_short_post = "inv_logit(rc_cuepostcue:freetimeshort) = inv_logit(rc_cuepostcue:freetimelong)"
  ))

Hyp_Model_OL2019_Exp4$hypothesis %>% mutate(Evid.Ratio = 1/Evid.Ratio)

#       Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio Post.Prob Star
# 1    a_cue_short   0.3017     0.508  -0.6781   1.3261      0.404     0.712     
# 2     a_cue_long  -0.3213     0.591  -1.5181   0.8153      0.471     0.680     
# 3    c_cue_short  -0.2459     0.365  -0.9593   0.4746      0.316     0.760     
# 4     c_cue_long   0.1801     0.426  -0.6565   1.0265      0.321     0.757     
# 5   ra_cue_short   0.2532     0.112   0.0273   0.4750      3.508     0.222    *
# 6    ra_cue_long   0.0785     0.156  -0.2347   0.3900      0.414     0.707     
# 7   rc_cue_short   0.0240     0.114  -0.2006   0.2419      0.286     0.777     
# 8    rc_cue_long   0.1932     0.114  -0.0448   0.4019      1.120     0.472     
# 9    a_short_pre  -0.5356     0.575  -1.7038   0.5644      0.612     0.620     
# 10  a_short_post   0.0874     0.526  -0.9538   1.1311      0.367     0.732     
# 11   c_short_pre  -0.3784     0.375  -1.1198   0.3603      0.445     0.692     
# 12  c_short_post  -0.8044     0.415  -1.6299   0.0101      1.983     0.335     
# 13  ra_short_pre   0.0614     0.134  -0.1949   0.3427      0.336     0.748     
# 14 ra_short_post   0.2361     0.137  -0.0255   0.5211      1.627     0.381     
# 15  rc_short_pre   0.1013     0.110  -0.1236   0.3053      0.428     0.700     
# 16 rc_short_post  -0.0679     0.119  -0.2980   0.1667      0.342     0.745     

```


## 3.6 Posteriors Distribution

### 3.6.1 Experiment 3

```{r}
Model_OL2019_Exp3 <- readRDS(paste0(model_path, "Model_M3_OL2019_Exp3.rds"))

Post_Exp3 <- Model_OL2019_Exp3 %>% 
  gather_draws(`b_.*`, regex = TRUE, ndraws = 8000) %>% 
  separate_wider_delim(.variable, "_", names = c(NA, "par", "effect"), cols_remove = TRUE) %>% 
  filter(par != "b") %>%
  separate_wider_delim(effect, ":", names = c("cue", "freetime"), cols_remove = TRUE) %>%
  rename(post = .value) %>% 
  mutate(
    cue = str_remove(cue, "cue"),
    freetime = str_remove(freetime, "freetime"),
    post = ifelse(str_detect(par, "r"),inv_logit_scaled(post), post))

write_csv(Post_Exp3, "./figures/figures_Data/Post_OL2019_Exp3.csv")

```

### 3.6.2 Experiment 4

```{r}
Model_OL2019_Exp4 <- readRDS(paste0(model_path, "Model_M3_OL2019_Exp4.rds"))

Post_Exp4 <- Model_OL2019_Exp4 %>% 
  gather_draws(`b_.*`, regex = TRUE, ndraws = 8000) %>% 
  separate_wider_delim(.variable, "_", names = c(NA, "par", "effect"), cols_remove = TRUE) %>% 
  mutate(n = ifelse(effect=="Intercept",4,1)) %>% 
  uncount(n, .id = "order") %>% 
  mutate(effect = case_when(
    effect=="Intercept" & order==1 ~ "cueprecue:freetimeshort",
    effect=="Intercept" & order==2 ~ "cueprecue:freetimelong",
    effect=="Intercept" & order==3 ~ "cuepostcue:freetimeshort",
    effect=="Intercept" & order==4 ~ "cuepostcue:freetimelong",
    TRUE ~ effect
  )) %>% 
  filter(par != "b") %>%
  separate_wider_delim(effect, ":", names = c("cue", "freetime"), cols_remove = TRUE) %>%
  rename(post = .value) %>% 
  mutate(
    cue = str_remove(cue, "cue"),
    freetime = str_remove(freetime, "freetime"),
    post = ifelse(str_detect(par, "r"),inv_logit_scaled(post), post))

write_csv(Post_Exp4, "./figures/figures_Data/Post_OL2019_Exp4.csv")

```


